version: '3'

services:
  postgres_db:
    container_name: tryitshipit_db
    image: postgres:11.2
    restart: always
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=narvar
      - POSTGRES_USER=narvar
      - POSTGRES_DB=tryitshipit
      - PGDATA=/var/lib/postgresql/data/pgdata

  load_the_data:
    container_name: data_loader
    image: postgres:11.2
    volumes:
    - ./db:/docker-entrypoint-initdb.d
    links:
    - postgres_db
    environment:
    - PGPASSWORD=narvar
    command: |
      sh -c "
        echo initializing schema
        cd /docker-entrypoint-initdb.d
        while [ true ]
        do
          echo \"trying to apply schema.\"
          psql -h postgres_db -U narvar -d tryitshipit -a -f schema.sql &&
          psql -h postgres_db -U narvar -d tryitshipit -a -f import_test_data.sql &&
          break
        done
      "

  maven:
    image: maven:3.6.0-jdk-8
    volumes:
    - ./:/root/.m2/
    - ~/.m2/repository:/root/.m2/repository
    command: |
      sh -c "
        sleep infinity
      "
    depends_on:
    - postgres_db
    - load_the_data

  tryitshipit:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    image: tryitshipit:latest
    ports:
    - "80:8080"
    depends_on:
    - postgres_db
    - load_the_data
    restart: on-failure
    environment:
    - spring.datasource.url=jdbc:postgresql://postgres_db:5432/tryitshipit

volumes:
  data: {}
